### ISSUE TITLE
Add some social proof to the homepage

### ISSUE THREAD

**Issue by cryppadotta** [delegatecash/delegatecash-website#1]
Hi! We're using delegate cash for the Forgotten Runes Halloween event which starts in 2 days (this Friday, [details here](https://medium.com/@dotta/your-invitation-to-trick-or-treat-at-the-nightmare-imps-door-and-partake-of-a-forgotten-runes-eb2ccf811816)).

I'm loving the new website design, but could you add a link to more information and some social proof to the new page? 

As it stands, there isn't any information as to who made this any longer and I'm worried it might turn some people off.

**Comment by ryeshrimp** [comment]
Hi @cryppadotta, I just added a twitter link to our socials. Will see what I can do to add some more information.
